### ISSUE TITLE
Logo disappears

### ISSUE THREAD

**Issue by bchugg** [CodeTheChangeUBC/ctc_site#41]
Going to another page and then returning to homepage via header sometimes results in no logo on main page.

**Comment by EWaterman** [comment]
`$(document).ready(function() {...}` is supposed to be called when the page loads but is not called when coming from an internal link. Probably because the page is already cached and pre-loaded.

`$(window).load(function() {...}` behaves similarly.

Potential solution would be to reload the homepage on arrival
